### ISSUE TITLE
Design Search Query Interface

### ISSUE THREAD

**Issue by varblob** [HackTheDinos/boneyard#5]
Wer'e going to need a nice interface for doing searches.  I really like the way close.io does their search.  Basically they have structured search by doing something like `Author:Bob` mixed with unstructured eg `Author:Bob femur` or full unstructured `Bob femur`.  There is a query builder that lets you create the structured bits of the search.

**Comment by heyitsolivia** [comment]
## ![boneyard-03](https://cloud.githubusercontent.com/assets/1198350/11324663/83f2f380-9106-11e5-8307-e6e2e7ed77f4.png)

## ![boneyard-01](https://cloud.githubusercontent.com/assets/1198350/11324661/83f03a14-9106-11e5-9631-c1314e4cadc6.png)

## ![boneyard-02](https://cloud.githubusercontent.com/assets/1198350/11324664/83f341fa-9106-11e5-9547-9106471ba21d.png)

![boneyard-04](https://cloud.githubusercontent.com/assets/1198350/11324662/83f26578-9106-11e5-8c74-dae3ade22acf.png)
